on:
  pull_request_target:
    types: [review_requested]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{ join(toJSON(github.event.action), '') }}
      - run: echo ${{ github.event.pull_request.requested_reviewer[0].login }}
      # - run: echo ${{ join(toJSON(github.event), '') }}
      # - run: echo ${{ toJSON(github.event.pull_request) }}
