on:
  pull_request_target:
    types: [review_requested]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.action }}
      - run: echo "============================"
      - run: echo ${{ github.event }}
      - run: echo "============================"
      - run: echo ${{ github.event.pull_request }}
