on:
  pull_request_target:
    types: [review_requested]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event.action) }}
      - run: echo "============================"
      - run: echo ${{ toJSON(github.event) }}
      - run: echo "============================"
      - run: echo ${{ toJSON(github.event.pull_request) }}
